// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: secdata_transfer.proto
// Original file comments:
// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_secdata_5ftransfer_2eproto__INCLUDED
#define GRPC_secdata_5ftransfer_2eproto__INCLUDED

#include "secdata_transfer.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc_impl {
class CompletionQueue;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc_impl

namespace grpc {
namespace experimental {
template <typename RequestT, typename ResponseT>
class MessageAllocator;
}  // namespace experimental
}  // namespace grpc

namespace secdata_transfer {

//  
class SecdataHandle final {
 public:
  static constexpr char const* service_full_name() {
    return "secdata_transfer.SecdataHandle";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Sends a greeting
    virtual ::grpc::Status TransferKlineData(::grpc::ClientContext* context, const ::secdata_transfer::KlineRequest& request, ::secdata_transfer::KlineReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::secdata_transfer::KlineReply>> AsyncTransferKlineData(::grpc::ClientContext* context, const ::secdata_transfer::KlineRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::secdata_transfer::KlineReply>>(AsyncTransferKlineDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::secdata_transfer::KlineReply>> PrepareAsyncTransferKlineData(::grpc::ClientContext* context, const ::secdata_transfer::KlineRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::secdata_transfer::KlineReply>>(PrepareAsyncTransferKlineDataRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // Sends a greeting
      virtual void TransferKlineData(::grpc::ClientContext* context, const ::secdata_transfer::KlineRequest* request, ::secdata_transfer::KlineReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void TransferKlineData(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::secdata_transfer::KlineReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void TransferKlineData(::grpc::ClientContext* context, const ::secdata_transfer::KlineRequest* request, ::secdata_transfer::KlineReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void TransferKlineData(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::secdata_transfer::KlineReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::secdata_transfer::KlineReply>* AsyncTransferKlineDataRaw(::grpc::ClientContext* context, const ::secdata_transfer::KlineRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::secdata_transfer::KlineReply>* PrepareAsyncTransferKlineDataRaw(::grpc::ClientContext* context, const ::secdata_transfer::KlineRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status TransferKlineData(::grpc::ClientContext* context, const ::secdata_transfer::KlineRequest& request, ::secdata_transfer::KlineReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::secdata_transfer::KlineReply>> AsyncTransferKlineData(::grpc::ClientContext* context, const ::secdata_transfer::KlineRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::secdata_transfer::KlineReply>>(AsyncTransferKlineDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::secdata_transfer::KlineReply>> PrepareAsyncTransferKlineData(::grpc::ClientContext* context, const ::secdata_transfer::KlineRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::secdata_transfer::KlineReply>>(PrepareAsyncTransferKlineDataRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void TransferKlineData(::grpc::ClientContext* context, const ::secdata_transfer::KlineRequest* request, ::secdata_transfer::KlineReply* response, std::function<void(::grpc::Status)>) override;
      void TransferKlineData(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::secdata_transfer::KlineReply* response, std::function<void(::grpc::Status)>) override;
      void TransferKlineData(::grpc::ClientContext* context, const ::secdata_transfer::KlineRequest* request, ::secdata_transfer::KlineReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void TransferKlineData(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::secdata_transfer::KlineReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::secdata_transfer::KlineReply>* AsyncTransferKlineDataRaw(::grpc::ClientContext* context, const ::secdata_transfer::KlineRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::secdata_transfer::KlineReply>* PrepareAsyncTransferKlineDataRaw(::grpc::ClientContext* context, const ::secdata_transfer::KlineRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_TransferKlineData_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Sends a greeting
    virtual ::grpc::Status TransferKlineData(::grpc::ServerContext* context, const ::secdata_transfer::KlineRequest* request, ::secdata_transfer::KlineReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_TransferKlineData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_TransferKlineData() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_TransferKlineData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TransferKlineData(::grpc::ServerContext* /*context*/, const ::secdata_transfer::KlineRequest* /*request*/, ::secdata_transfer::KlineReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTransferKlineData(::grpc::ServerContext* context, ::secdata_transfer::KlineRequest* request, ::grpc::ServerAsyncResponseWriter< ::secdata_transfer::KlineReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_TransferKlineData<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_TransferKlineData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_TransferKlineData() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc_impl::internal::CallbackUnaryHandler< ::secdata_transfer::KlineRequest, ::secdata_transfer::KlineReply>(
          [this](::grpc::ServerContext* context,
                 const ::secdata_transfer::KlineRequest* request,
                 ::secdata_transfer::KlineReply* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->TransferKlineData(context, request, response, controller);
                 }));
    }
    void SetMessageAllocatorFor_TransferKlineData(
        ::grpc::experimental::MessageAllocator< ::secdata_transfer::KlineRequest, ::secdata_transfer::KlineReply>* allocator) {
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::secdata_transfer::KlineRequest, ::secdata_transfer::KlineReply>*>(
          ::grpc::Service::experimental().GetHandler(0))
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_TransferKlineData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TransferKlineData(::grpc::ServerContext* /*context*/, const ::secdata_transfer::KlineRequest* /*request*/, ::secdata_transfer::KlineReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void TransferKlineData(::grpc::ServerContext* /*context*/, const ::secdata_transfer::KlineRequest* /*request*/, ::secdata_transfer::KlineReply* /*response*/, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_TransferKlineData<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_TransferKlineData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_TransferKlineData() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_TransferKlineData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TransferKlineData(::grpc::ServerContext* /*context*/, const ::secdata_transfer::KlineRequest* /*request*/, ::secdata_transfer::KlineReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_TransferKlineData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_TransferKlineData() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_TransferKlineData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TransferKlineData(::grpc::ServerContext* /*context*/, const ::secdata_transfer::KlineRequest* /*request*/, ::secdata_transfer::KlineReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTransferKlineData(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_TransferKlineData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_TransferKlineData() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->TransferKlineData(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_TransferKlineData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TransferKlineData(::grpc::ServerContext* /*context*/, const ::secdata_transfer::KlineRequest* /*request*/, ::secdata_transfer::KlineReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void TransferKlineData(::grpc::ServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_TransferKlineData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_TransferKlineData() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::secdata_transfer::KlineRequest, ::secdata_transfer::KlineReply>(std::bind(&WithStreamedUnaryMethod_TransferKlineData<BaseClass>::StreamedTransferKlineData, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_TransferKlineData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status TransferKlineData(::grpc::ServerContext* /*context*/, const ::secdata_transfer::KlineRequest* /*request*/, ::secdata_transfer::KlineReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedTransferKlineData(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::secdata_transfer::KlineRequest,::secdata_transfer::KlineReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_TransferKlineData<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_TransferKlineData<Service > StreamedService;
};

}  // namespace secdata_transfer


#endif  // GRPC_secdata_5ftransfer_2eproto__INCLUDED
