// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: zen_data_svr.proto
// Original file comments:
// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_zen_5fdata_5fsvr_2eproto__INCLUDED
#define GRPC_zen_5fdata_5fsvr_2eproto__INCLUDED

#include "zen_data_svr.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc_impl {
class CompletionQueue;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc_impl

namespace grpc {
namespace experimental {
template <typename RequestT, typename ResponseT>
class MessageAllocator;
}  // namespace experimental
}  // namespace grpc

namespace zen_data_svr {

//  
class ZendataHandle final {
 public:
  static constexpr char const* service_full_name() {
    return "zen_data_svr.ZendataHandle";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status PushKlineData(::grpc::ClientContext* context, const ::zen_data_svr::PushKlineReq& request, ::zen_data_svr::PushKlineRsp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::zen_data_svr::PushKlineRsp>> AsyncPushKlineData(::grpc::ClientContext* context, const ::zen_data_svr::PushKlineReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::zen_data_svr::PushKlineRsp>>(AsyncPushKlineDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::zen_data_svr::PushKlineRsp>> PrepareAsyncPushKlineData(::grpc::ClientContext* context, const ::zen_data_svr::PushKlineReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::zen_data_svr::PushKlineRsp>>(PrepareAsyncPushKlineDataRaw(context, request, cq));
    }
    virtual ::grpc::Status AskKlineData(::grpc::ClientContext* context, const ::zen_data_svr::AskKlineReq& request, ::zen_data_svr::AskKlineRsp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::zen_data_svr::AskKlineRsp>> AsyncAskKlineData(::grpc::ClientContext* context, const ::zen_data_svr::AskKlineReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::zen_data_svr::AskKlineRsp>>(AsyncAskKlineDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::zen_data_svr::AskKlineRsp>> PrepareAsyncAskKlineData(::grpc::ClientContext* context, const ::zen_data_svr::AskKlineReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::zen_data_svr::AskKlineRsp>>(PrepareAsyncAskKlineDataRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void PushKlineData(::grpc::ClientContext* context, const ::zen_data_svr::PushKlineReq* request, ::zen_data_svr::PushKlineRsp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void PushKlineData(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::zen_data_svr::PushKlineRsp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void PushKlineData(::grpc::ClientContext* context, const ::zen_data_svr::PushKlineReq* request, ::zen_data_svr::PushKlineRsp* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void PushKlineData(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::zen_data_svr::PushKlineRsp* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void AskKlineData(::grpc::ClientContext* context, const ::zen_data_svr::AskKlineReq* request, ::zen_data_svr::AskKlineRsp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AskKlineData(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::zen_data_svr::AskKlineRsp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AskKlineData(::grpc::ClientContext* context, const ::zen_data_svr::AskKlineReq* request, ::zen_data_svr::AskKlineRsp* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void AskKlineData(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::zen_data_svr::AskKlineRsp* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::zen_data_svr::PushKlineRsp>* AsyncPushKlineDataRaw(::grpc::ClientContext* context, const ::zen_data_svr::PushKlineReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::zen_data_svr::PushKlineRsp>* PrepareAsyncPushKlineDataRaw(::grpc::ClientContext* context, const ::zen_data_svr::PushKlineReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::zen_data_svr::AskKlineRsp>* AsyncAskKlineDataRaw(::grpc::ClientContext* context, const ::zen_data_svr::AskKlineReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::zen_data_svr::AskKlineRsp>* PrepareAsyncAskKlineDataRaw(::grpc::ClientContext* context, const ::zen_data_svr::AskKlineReq& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status PushKlineData(::grpc::ClientContext* context, const ::zen_data_svr::PushKlineReq& request, ::zen_data_svr::PushKlineRsp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::zen_data_svr::PushKlineRsp>> AsyncPushKlineData(::grpc::ClientContext* context, const ::zen_data_svr::PushKlineReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::zen_data_svr::PushKlineRsp>>(AsyncPushKlineDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::zen_data_svr::PushKlineRsp>> PrepareAsyncPushKlineData(::grpc::ClientContext* context, const ::zen_data_svr::PushKlineReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::zen_data_svr::PushKlineRsp>>(PrepareAsyncPushKlineDataRaw(context, request, cq));
    }
    ::grpc::Status AskKlineData(::grpc::ClientContext* context, const ::zen_data_svr::AskKlineReq& request, ::zen_data_svr::AskKlineRsp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::zen_data_svr::AskKlineRsp>> AsyncAskKlineData(::grpc::ClientContext* context, const ::zen_data_svr::AskKlineReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::zen_data_svr::AskKlineRsp>>(AsyncAskKlineDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::zen_data_svr::AskKlineRsp>> PrepareAsyncAskKlineData(::grpc::ClientContext* context, const ::zen_data_svr::AskKlineReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::zen_data_svr::AskKlineRsp>>(PrepareAsyncAskKlineDataRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void PushKlineData(::grpc::ClientContext* context, const ::zen_data_svr::PushKlineReq* request, ::zen_data_svr::PushKlineRsp* response, std::function<void(::grpc::Status)>) override;
      void PushKlineData(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::zen_data_svr::PushKlineRsp* response, std::function<void(::grpc::Status)>) override;
      void PushKlineData(::grpc::ClientContext* context, const ::zen_data_svr::PushKlineReq* request, ::zen_data_svr::PushKlineRsp* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void PushKlineData(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::zen_data_svr::PushKlineRsp* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void AskKlineData(::grpc::ClientContext* context, const ::zen_data_svr::AskKlineReq* request, ::zen_data_svr::AskKlineRsp* response, std::function<void(::grpc::Status)>) override;
      void AskKlineData(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::zen_data_svr::AskKlineRsp* response, std::function<void(::grpc::Status)>) override;
      void AskKlineData(::grpc::ClientContext* context, const ::zen_data_svr::AskKlineReq* request, ::zen_data_svr::AskKlineRsp* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void AskKlineData(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::zen_data_svr::AskKlineRsp* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::zen_data_svr::PushKlineRsp>* AsyncPushKlineDataRaw(::grpc::ClientContext* context, const ::zen_data_svr::PushKlineReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::zen_data_svr::PushKlineRsp>* PrepareAsyncPushKlineDataRaw(::grpc::ClientContext* context, const ::zen_data_svr::PushKlineReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::zen_data_svr::AskKlineRsp>* AsyncAskKlineDataRaw(::grpc::ClientContext* context, const ::zen_data_svr::AskKlineReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::zen_data_svr::AskKlineRsp>* PrepareAsyncAskKlineDataRaw(::grpc::ClientContext* context, const ::zen_data_svr::AskKlineReq& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_PushKlineData_;
    const ::grpc::internal::RpcMethod rpcmethod_AskKlineData_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status PushKlineData(::grpc::ServerContext* context, const ::zen_data_svr::PushKlineReq* request, ::zen_data_svr::PushKlineRsp* response);
    virtual ::grpc::Status AskKlineData(::grpc::ServerContext* context, const ::zen_data_svr::AskKlineReq* request, ::zen_data_svr::AskKlineRsp* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_PushKlineData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PushKlineData() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_PushKlineData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PushKlineData(::grpc::ServerContext* /*context*/, const ::zen_data_svr::PushKlineReq* /*request*/, ::zen_data_svr::PushKlineRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPushKlineData(::grpc::ServerContext* context, ::zen_data_svr::PushKlineReq* request, ::grpc::ServerAsyncResponseWriter< ::zen_data_svr::PushKlineRsp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_AskKlineData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AskKlineData() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_AskKlineData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AskKlineData(::grpc::ServerContext* /*context*/, const ::zen_data_svr::AskKlineReq* /*request*/, ::zen_data_svr::AskKlineRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAskKlineData(::grpc::ServerContext* context, ::zen_data_svr::AskKlineReq* request, ::grpc::ServerAsyncResponseWriter< ::zen_data_svr::AskKlineRsp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_PushKlineData<WithAsyncMethod_AskKlineData<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_PushKlineData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_PushKlineData() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc_impl::internal::CallbackUnaryHandler< ::zen_data_svr::PushKlineReq, ::zen_data_svr::PushKlineRsp>(
          [this](::grpc::ServerContext* context,
                 const ::zen_data_svr::PushKlineReq* request,
                 ::zen_data_svr::PushKlineRsp* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->PushKlineData(context, request, response, controller);
                 }));
    }
    void SetMessageAllocatorFor_PushKlineData(
        ::grpc::experimental::MessageAllocator< ::zen_data_svr::PushKlineReq, ::zen_data_svr::PushKlineRsp>* allocator) {
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::zen_data_svr::PushKlineReq, ::zen_data_svr::PushKlineRsp>*>(
          ::grpc::Service::experimental().GetHandler(0))
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_PushKlineData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PushKlineData(::grpc::ServerContext* /*context*/, const ::zen_data_svr::PushKlineReq* /*request*/, ::zen_data_svr::PushKlineRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void PushKlineData(::grpc::ServerContext* /*context*/, const ::zen_data_svr::PushKlineReq* /*request*/, ::zen_data_svr::PushKlineRsp* /*response*/, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_AskKlineData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_AskKlineData() {
      ::grpc::Service::experimental().MarkMethodCallback(1,
        new ::grpc_impl::internal::CallbackUnaryHandler< ::zen_data_svr::AskKlineReq, ::zen_data_svr::AskKlineRsp>(
          [this](::grpc::ServerContext* context,
                 const ::zen_data_svr::AskKlineReq* request,
                 ::zen_data_svr::AskKlineRsp* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->AskKlineData(context, request, response, controller);
                 }));
    }
    void SetMessageAllocatorFor_AskKlineData(
        ::grpc::experimental::MessageAllocator< ::zen_data_svr::AskKlineReq, ::zen_data_svr::AskKlineRsp>* allocator) {
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::zen_data_svr::AskKlineReq, ::zen_data_svr::AskKlineRsp>*>(
          ::grpc::Service::experimental().GetHandler(1))
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_AskKlineData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AskKlineData(::grpc::ServerContext* /*context*/, const ::zen_data_svr::AskKlineReq* /*request*/, ::zen_data_svr::AskKlineRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void AskKlineData(::grpc::ServerContext* /*context*/, const ::zen_data_svr::AskKlineReq* /*request*/, ::zen_data_svr::AskKlineRsp* /*response*/, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_PushKlineData<ExperimentalWithCallbackMethod_AskKlineData<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_PushKlineData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PushKlineData() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_PushKlineData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PushKlineData(::grpc::ServerContext* /*context*/, const ::zen_data_svr::PushKlineReq* /*request*/, ::zen_data_svr::PushKlineRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_AskKlineData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AskKlineData() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_AskKlineData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AskKlineData(::grpc::ServerContext* /*context*/, const ::zen_data_svr::AskKlineReq* /*request*/, ::zen_data_svr::AskKlineRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_PushKlineData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PushKlineData() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_PushKlineData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PushKlineData(::grpc::ServerContext* /*context*/, const ::zen_data_svr::PushKlineReq* /*request*/, ::zen_data_svr::PushKlineRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPushKlineData(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_AskKlineData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AskKlineData() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_AskKlineData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AskKlineData(::grpc::ServerContext* /*context*/, const ::zen_data_svr::AskKlineReq* /*request*/, ::zen_data_svr::AskKlineRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAskKlineData(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_PushKlineData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_PushKlineData() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->PushKlineData(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_PushKlineData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PushKlineData(::grpc::ServerContext* /*context*/, const ::zen_data_svr::PushKlineReq* /*request*/, ::zen_data_svr::PushKlineRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void PushKlineData(::grpc::ServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_AskKlineData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_AskKlineData() {
      ::grpc::Service::experimental().MarkMethodRawCallback(1,
        new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->AskKlineData(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_AskKlineData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AskKlineData(::grpc::ServerContext* /*context*/, const ::zen_data_svr::AskKlineReq* /*request*/, ::zen_data_svr::AskKlineRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void AskKlineData(::grpc::ServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PushKlineData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_PushKlineData() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::zen_data_svr::PushKlineReq, ::zen_data_svr::PushKlineRsp>(std::bind(&WithStreamedUnaryMethod_PushKlineData<BaseClass>::StreamedPushKlineData, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_PushKlineData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PushKlineData(::grpc::ServerContext* /*context*/, const ::zen_data_svr::PushKlineReq* /*request*/, ::zen_data_svr::PushKlineRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPushKlineData(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::zen_data_svr::PushKlineReq,::zen_data_svr::PushKlineRsp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AskKlineData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AskKlineData() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< ::zen_data_svr::AskKlineReq, ::zen_data_svr::AskKlineRsp>(std::bind(&WithStreamedUnaryMethod_AskKlineData<BaseClass>::StreamedAskKlineData, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_AskKlineData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AskKlineData(::grpc::ServerContext* /*context*/, const ::zen_data_svr::AskKlineReq* /*request*/, ::zen_data_svr::AskKlineRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAskKlineData(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::zen_data_svr::AskKlineReq,::zen_data_svr::AskKlineRsp>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_PushKlineData<WithStreamedUnaryMethod_AskKlineData<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_PushKlineData<WithStreamedUnaryMethod_AskKlineData<Service > > StreamedService;
};

}  // namespace zen_data_svr


#endif  // GRPC_zen_5fdata_5fsvr_2eproto__INCLUDED
